name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.10'

      - name: Prepare project
        run: |
          mkdir -p app/src/main/java/com/example/s26basilitut
          mkdir -p app/src/main/res/xml
          mkdir -p app/src/main/res/values

          mv AndroidManifest.xml app/src/main/
          mv HoldAccessibilityService.java app/src/main/java/com/example/s26basilitut/
          mv MainActivity.java app/src/main/java/com/example/s26basilitut/
          mv accessibility_service_config.xml app/src/main/res/xml/
          mv strings.xml app/src/main/res/values/
          mv styles.xml app/src/main/res/values/

      - name: Build APK
        run: gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: S26-Basili-Tut
          path: app/build/outputs/apk/debug/app-debug.apk
